// Code generated by "stringer -type=RuntimeType -trimprefix=RuntimeType -output=runtime_type_string.go"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RuntimeTypeWASM-0]
	_ = x[RuntimeTypeJS-1]
}

const _RuntimeType_name = "WASMJS"

var _RuntimeType_index = [...]uint8{0, 4, 6}

func (i RuntimeType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RuntimeType_index)-1 {
		return "RuntimeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RuntimeType_name[_RuntimeType_index[idx]:_RuntimeType_index[idx+1]]
}
