// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: types/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FDRequest struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	Method           string                   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Header           map[string]*HeaderFields `protobuf:"bytes,2,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body             []byte                   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	ContentLength    int64                    `protobuf:"varint,4,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	TransferEncoding *StringSlice             `protobuf:"bytes,5,opt,name=transfer_encoding,json=transferEncoding,proto3" json:"transfer_encoding,omitempty"`
	Host             string                   `protobuf:"bytes,6,opt,name=host,proto3" json:"host,omitempty"`
	RemoteAddr       string                   `protobuf:"bytes,7,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	RequestUri       string                   `protobuf:"bytes,8,opt,name=request_uri,json=requestUri,proto3" json:"request_uri,omitempty"`
	Pattern          string                   `protobuf:"bytes,9,opt,name=pattern,proto3" json:"pattern,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FDRequest) Reset() {
	*x = FDRequest{}
	mi := &file_types_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FDRequest) ProtoMessage() {}

func (x *FDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FDRequest.ProtoReflect.Descriptor instead.
func (*FDRequest) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{0}
}

func (x *FDRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *FDRequest) GetHeader() map[string]*HeaderFields {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FDRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *FDRequest) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

func (x *FDRequest) GetTransferEncoding() *StringSlice {
	if x != nil {
		return x.TransferEncoding
	}
	return nil
}

func (x *FDRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *FDRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *FDRequest) GetRequestUri() string {
	if x != nil {
		return x.RequestUri
	}
	return ""
}

func (x *FDRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

type FDResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Body          []byte                   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	StatusCode    int32                    `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Length        int32                    `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	Header        map[string]*HeaderFields `protobuf:"bytes,4,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FDResponse) Reset() {
	*x = FDResponse{}
	mi := &file_types_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FDResponse) ProtoMessage() {}

func (x *FDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FDResponse.ProtoReflect.Descriptor instead.
func (*FDResponse) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{1}
}

func (x *FDResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *FDResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *FDResponse) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *FDResponse) GetHeader() map[string]*HeaderFields {
	if x != nil {
		return x.Header
	}
	return nil
}

type HeaderFields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []string               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderFields) Reset() {
	*x = HeaderFields{}
	mi := &file_types_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderFields) ProtoMessage() {}

func (x *HeaderFields) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderFields.ProtoReflect.Descriptor instead.
func (*HeaderFields) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{2}
}

func (x *HeaderFields) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type StringSlice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []string               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringSlice) Reset() {
	*x = StringSlice{}
	mi := &file_types_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringSlice) ProtoMessage() {}

func (x *StringSlice) ProtoReflect() protoreflect.Message {
	mi := &file_types_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringSlice.ProtoReflect.Descriptor instead.
func (*StringSlice) Descriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{3}
}

func (x *StringSlice) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_types_types_proto protoreflect.FileDescriptor

const file_types_types_proto_rawDesc = "" +
	"\n" +
	"\x11types/types.proto\x12\x05types\"\x95\x03\n" +
	"\tFDRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x124\n" +
	"\x06header\x18\x02 \x03(\v2\x1c.types.FDRequest.HeaderEntryR\x06header\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12%\n" +
	"\x0econtent_length\x18\x04 \x01(\x03R\rcontentLength\x12?\n" +
	"\x11transfer_encoding\x18\x05 \x01(\v2\x12.types.StringSliceR\x10transferEncoding\x12\x12\n" +
	"\x04host\x18\x06 \x01(\tR\x04host\x12\x1f\n" +
	"\vremote_addr\x18\a \x01(\tR\n" +
	"remoteAddr\x12\x1f\n" +
	"\vrequest_uri\x18\b \x01(\tR\n" +
	"requestUri\x12\x18\n" +
	"\apattern\x18\t \x01(\tR\apattern\x1aN\n" +
	"\vHeaderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.types.HeaderFieldsR\x05value:\x028\x01\"\xe0\x01\n" +
	"\n" +
	"FDResponse\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x05R\x06length\x125\n" +
	"\x06header\x18\x04 \x03(\v2\x1d.types.FDResponse.HeaderEntryR\x06header\x1aN\n" +
	"\vHeaderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.types.HeaderFieldsR\x05value:\x028\x01\"&\n" +
	"\fHeaderFields\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fields\"%\n" +
	"\vStringSlice\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fieldsB\x16Z\x14ignis-wasmtime/typesb\x06proto3"

var (
	file_types_types_proto_rawDescOnce sync.Once
	file_types_types_proto_rawDescData []byte
)

func file_types_types_proto_rawDescGZIP() []byte {
	file_types_types_proto_rawDescOnce.Do(func() {
		file_types_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_types_proto_rawDesc), len(file_types_types_proto_rawDesc)))
	})
	return file_types_types_proto_rawDescData
}

var file_types_types_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_types_types_proto_goTypes = []any{
	(*FDRequest)(nil),    // 0: types.FDRequest
	(*FDResponse)(nil),   // 1: types.FDResponse
	(*HeaderFields)(nil), // 2: types.HeaderFields
	(*StringSlice)(nil),  // 3: types.StringSlice
	nil,                  // 4: types.FDRequest.HeaderEntry
	nil,                  // 5: types.FDResponse.HeaderEntry
}
var file_types_types_proto_depIdxs = []int32{
	4, // 0: types.FDRequest.header:type_name -> types.FDRequest.HeaderEntry
	3, // 1: types.FDRequest.transfer_encoding:type_name -> types.StringSlice
	5, // 2: types.FDResponse.header:type_name -> types.FDResponse.HeaderEntry
	2, // 3: types.FDRequest.HeaderEntry.value:type_name -> types.HeaderFields
	2, // 4: types.FDResponse.HeaderEntry.value:type_name -> types.HeaderFields
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_types_types_proto_init() }
func file_types_types_proto_init() {
	if File_types_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_types_proto_rawDesc), len(file_types_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_types_proto_goTypes,
		DependencyIndexes: file_types_types_proto_depIdxs,
		MessageInfos:      file_types_types_proto_msgTypes,
	}.Build()
	File_types_types_proto = out.File
	file_types_types_proto_goTypes = nil
	file_types_types_proto_depIdxs = nil
}
